name: ROS 2 CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test the project
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Building and testing
        uses: threeal/ros2-ci@v0.4.1
        with:
          ros2-distro: foxy
          apt-packages: git ros-foxy-gazebo-ros
          pre-build: git clone https://github.com/threeal/tosshin_interfaces /ws/tosshin_interfaces
